Flask_FullStack_Ecommerce_App-main/website/auth.py
from flask import Blueprint, render_template, session, request, redirect, url_for, flash
import sqlite3
auth = Blueprint("auth", __name__)

sqldbname = 'LAPTRINHWEB.db'

def SaveToDB(name,email,password):
    conn = sqlite3.connect(sqldbname)
    cur = conn.cursor()
    sqlcommand = "SELECT Max(user_id) from user"
    cur.execute(sqlcommand)
    id_max = cur.fetchone()[0]
    id_max = id_max + 1
    cur.execute("INSERT INTO user (user_id, name, email, password) VALUES (?,?,?,?)",(id_max,name,email,password))
    conn.commit()
    conn.close()
    return id_max

def get_obj_user(username,password):
    result =[]
    conn = sqlite3.connect(sqldbname)
    cur = conn.cursor()
    sqlcommand = "Select * from user where email =? and password = ?"
    cur.execute(sqlcommand,(username,password))
    obj_user = cur.fetchone()
    if obj_user:
        result = obj_user
    conn.close()
    return result;


@auth.route('/login', methods = ['GET','POST'])
def login():
    if request.method == 'POST':
        username = request.form['txt_username']
        password = request.form['txt_password']
        obj_user = get_obj_user(username,password)
        if obj_user:
            obj_user ={
                "id" : obj_user[0],
                "name": obj_user[1],
                "email":obj_user[2]
            }
            session['current_user'] = obj_user
            flash("You have log in successfully", "success")
            return redirect(url_for('views.account'))
        flash("Please check your username and password", 'error')
        return redirect(url_for('auth.login'))
    return render_template('login.html')

@auth.route("/signup", methods=['GET','POST'])
def sign_up():
  if request.method == 'POST':
    username = request.form['username']
    email = request.form['email']
    password = request.form['password']
    username_error = ""
    email_error = ""
    password_error = ""
    if not username:
      username_error = "Username is required."
    if not password: 
      password_error = "Password is required."
    if not email: 
      email_error = "Email is required."
    if username_error or password_error or email_error:
      return render_template("signup.html", username_error = username_error, password_error =password_error, email_error =email_error, registeration_success = "")
    newid = SaveToDB(username, email, password)
    flash("You have sign up successfully", "success")
    return redirect(url_for("auth.login"))
    # stroutput = f'Registered: Username: {username},Email: {email}, Password: {password}'
    # registeration_success = "Registeration successful with id = "+ str(newid)
    
  return render_template("signup.html")
  

@auth.route("/logout")
def logout():
    session.pop('current_user', None)
    session.pop('cart', None)
    return redirect(url_for('views.home'))

Flask_FullStack_Ecommerce_App-main/website/views.py
from flask import Blueprint, render_template, request, session, flash, redirect, url_for
import sqlite3
views = Blueprint("views", __name__)


sqldbname = 'LAPTRINHWEB.db'
@views.context_processor
def my_utility_processor():
    def convert_currency_to_int(currency_str):
        currency_str = currency_str.replace("$", "").replace(".", "")
        return int(currency_str)
    def convert_int_to_currency(number):
        number_str = str(number)
        currency_str = ""
        count = 0

        for digit in reversed(number_str):
            if count != 0 and count % 3 == 0:
                currency_str = "." + currency_str
            currency_str = digit + currency_str
            count += 1

        currency_str = "$" + currency_str
        return currency_str
    return dict(convert_currency_to_int=convert_currency_to_int, convert_int_to_currency=convert_int_to_currency)

@views.route('/')
def home():
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    conn = sqlite3.connect(sqldbname)
    cursor = conn.cursor()
    sqlcommand = 'SELECT * FROM FASHION LIMIT 0, 4'
    cursor.execute(sqlcommand)
    featuresProduct = cursor.fetchall()
    sqlcommand = 'SELECT * FROM FASHION LIMIT 4, 10'
    cursor.execute(sqlcommand)
    latestProducts = cursor.fetchall()
    return render_template('home.html', featuresProduct=featuresProduct, latestProducts=latestProducts,user_name = current_username)

@views.route('/cart', methods=['GET'])
def shopping_cart():
    current_username = ""
    current_cart = []
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    if 'cart' in session:
        current_cart = session.get('cart', [])

    return render_template('cart.html', cart=current_cart,user_name = current_username)

@views.route('/all_products')
def all_products():
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    conn = sqlite3.connect(sqldbname)
    cursor = conn.cursor()
    sqlcommand = 'SELECT * FROM FASHION'
    cursor.execute(sqlcommand)
    all_products = cursor.fetchall()
    return render_template('all_products.html', all_products=all_products,user_name = current_username)

@views.route('/product_detail/<id>')
def product_detail(id):
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    conn = sqlite3.connect(sqldbname)
    cursor = conn.cursor()
    sqlcommand = 'SELECT * FROM FASHION WHERE id = ?'
    cursor.execute(sqlcommand, (id,))
    product_detail = cursor.fetchone()
    sqlcommand = 'SELECT * FROM FASHION LIMIT 0, 4'
    cursor.execute(sqlcommand)
    related_products = cursor.fetchall()
    return render_template('product_detail.html', product_detail=product_detail, related_products=related_products, user_name = current_username)

@views.route('/about')
def about():
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    return render_template('about.html' ,user_name = current_username)


@views.route('/contact', methods=['GET', 'POST'])
def contact():
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    if request.method == 'POST':
        Name = request.form['Name']
        Tel = request.form['Tel']
        Email = request.form['Email']
        Message = request.form['message']
        flash("Thank you for your feedback", "success")
        return redirect(url_for('views.contact'))
    return render_template('contact.html',user_name = current_username)

@views.route('/cart/add', methods=['POST'])
def addToCart():
    productId = request.form['product_id']
    quantity = int(request.form['quantity'])
    conn = sqlite3.connect(sqldbname)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT product, price, picture FROM FASHION WHERE id = ?", (productId,))
    product = cursor.fetchone()
    conn.close()
    product_detail = {
        "id": productId,
        "name": product[0],
        "price": product[1],
        "image": product[2],
        "quantity": quantity
    }
    cart = session.get('cart', [])
    found = False
    for item in cart:
        if item["id"] == productId:
            item["quantity"] += quantity
            found = True
            break
    if not found:
        cart.append(product_detail)
    session["cart"] = cart
    rows = len(cart)
    flash('Item added successfully!', 'success')
    return redirect(url_for('views.product_detail', id=productId))

@views.route('/cart/update',methods = ['POST'])
def CartUpdate():
    cart = session.get('cart', [])
    new_cart = []
    for row in cart:
        productId = int(row['id'])
        if f'quantity-{productId}' in request.form:
            quantity = int(request.form[f'quantity-{productId}'])
            if quantity == 0 or f'delete-{productId}' in request.form:
                continue
            row['quantity'] = quantity
        new_cart.append(row)
    session['cart'] = new_cart
    return redirect(url_for('views.shopping_cart'))

@views.route('/proceed_cart',methods = ['POST'] )
def proceed_cart():
    if 'current_user' in session:
        user_id = session['current_user']['id']
        user_email = session['current_user']['email']
        if 'cart' in session:
            current_cart = session.get("cart",[])
            if current_cart is not []:
                conn = sqlite3.connect(sqldbname)
                cur = conn.cursor()
                status = 1
                cur.execute('INSERT INTO "order" (user_id, user_email,status) VALUES(?, ?, ?)',(user_id,user_email,status))
                order_id = cur.lastrowid
                for product in current_cart:
                    product_id = product['id']
                    price = product['price']
                    quantity = product['quantity']
                    cur.execute('INSERT or REPLACE INTO "order_details" (order_id, product_id, price, quantity) VALUES(?,?,?,?)',(order_id,product_id,price,quantity))  
                conn.commit()
                conn.close()
                if 'cart' in session:
                    current_cart = session.pop("cart",[])
                flash(f'Your order has been successfully created: orderID: {order_id}')
                return redirect(url_for("views.account"))  
        flash("There is nothing in cart. Let's add some!", "info")
        return redirect(url_for("views.all_products"))
    flash("You are not logged in. Please login", "error")
    return redirect(url_for("auth.login"))
    

@views.route('/account/',methods = ['GET'])
def account():
    user_orders = []
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    user_id = session.get('current_user',{}).get('id')
    if user_id:
        conn = sqlite3.connect(sqldbname)
        cur = conn.cursor()
        cur.execute('Select * from "order" where user_id = ?',(user_id,))
        user_orders = cur.fetchall()
        conn.close()
        return render_template('account.html',orders = user_orders, user_name = current_username)
    flash("User not logged in")
    return redirect(url_for("auth.login"))

@views.route('/order/', defaults={'order_id':None}, methods = ['GET'])
@views.route('/order/<int:order_id>/', methods = ['GET'])
def order(order_id):
    current_username = ""
    if 'current_user' in session:
        current_username = session['current_user']['name']
    else:
        current_username = ""
    user_id = session.get('current_user',{}).get('id')
    if user_id:
        conn = sqlite3.connect(sqldbname)
        cur = conn.cursor()
        if order_id is not None:
            cur.execute('Select * from "order" where id = ? and user_id = ?',(order_id,user_id))
            order = cur.fetchone()
            cur.execute('SELECT * from order_details where order_id = ?',(order_id,))
            order_details = cur.fetchall()
            conn.close()
            return render_template('orders.html',order = order,order_details = order_details, user_name = current_username)
        else:
            cur.execute('Select * from "order" where user_id = ?',(user_id,))
            user_orders = cur.fetchall()
            if not user_orders:
                user_orders = None
            conn.close()
            return render_template('account.html',orders = user_orders, user_name = current_username)
    flash("User not logged in")
    return redirect(url_for("auth.login"))

@views.route("/sort-form", methods=["POST"])
def process_sort_form():
    selected_option = request.form.get('sort-dropdown')
    conn = sqlite3.connect(sqldbname)
    cursor = conn.cursor()
    match selected_option:
        case "Default Sort":
            sqlcommand = ("select * from FASHION")
        case "Sort By Price":
            sqlcommand = ("select * from FASHION ORDER BY CAST(REPLACE(REPLACE(price, '$', ''), '.', '') AS INT)")
        case "Sort By Price DESC":
            sqlcommand = ("select * from FASHION ORDER BY CAST(REPLACE(REPLACE(price, '$', ''), '.', '') AS INT) DESC")
        case "Sort By Rating":
            sqlcommand = ("select * from FASHION ORDER BY rating DESC")
        case "Sort By Brand":        
            sqlcommand = ("select * from FASHION ORDER BY brand")

Flask_FullStack_Ecommerce_App-main/website/templates/about.html
{%extends "base.html"%} {% block title%}Verve & Co. | About{%endblock%} {% block
content%}

<section class="container">
  <div style="font-size: 2.5rem; margin: 2rem 0; font-weight: 500; text-align:center">
    About Verve & Co.
  </div>
  <div class="row">
    <div class="col-2">
      <img
        class="about-img"
        src="https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=600"
        alt="clothes images"
      />
    </div>
    <div class="col-2">
      <h2>Who are we</h2>
      <p>
        Welcome to Verve & Co., your ultimate destination for fashion-forward
        clothing and accessories. We pride ourselves on curating a diverse
        collection of stylish garments that cater to individuals who seek to
        express their unique personality through fashion. With a deep passion
        for all things trendy and a commitment to exceptional customer service,
        we strive to provide a memorable shopping experience that exceeds your
        expectations.
      </p><br>
      <p>
        At Verve & Co., we are a team of fashion enthusiasts who believe that
        clothing is more than just fabric; it's a means of self-expression and a
        reflection of your individuality. We understand the power of fashion to
        boost confidence and make a statement. That's why we carefully select
        each piece in our collection, ensuring that it embodies the latest
        trends while maintaining high-quality standards. Our team is dedicated
        to staying ahead of the fashion curve and bringing you the freshest
        styles from both established designers and emerging brands.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <h2>Our Products</h2>
      <p>
        Our collection features a wide range of clothing and accessories to suit
        every style and occasion. From casual everyday wear to glamorous evening
        attire, we have something for everyone. Discover chic dresses that
        effortlessly transition from day to night, comfortable and trendy
        loungewear for those cozy moments, smart and sophisticated workwear that
        exudes professionalism, and a variety of accessories to complement and
        elevate your look.
      </p>
      <br />
      <p>
        We understand that fashion is not one-size-fits-all, which is why we
        offer a diverse range of sizes, cuts, and styles to ensure inclusivity
        and to cater to a variety of body types and preferences. Our commitment
        to quality is unwavering, and we carefully handpick each item to ensure
        that it meets our stringent standards of craftsmanship, durability, and
        style.
      </p>
    </div>
    <div class="col-2">
      <img
        class="about-img"
        src="https://images.pexels.com/photos/4641825/pexels-photo-4641825.jpeg?auto=compress&cs=tinysrgb&w=600"
        alt="clothes images"
      />
    </div>
  </div>
  <div class="row">
    <h2>Our Commitment</h2>
    <p class="about-para">
      At Verve & Co., your satisfaction is our top priority. We are committed to
      providing exceptional customer service at every step of your shopping
      journey. Our knowledgeable and friendly team is here to assist you with
      any inquiries, sizing concerns, or styling advice you may need. We believe
      in building lasting relationships with our customers and strive to create
      an environment where you feel valued and supported.
    </p>
    <p class="about-para">
      We are dedicated to creating a seamless online shopping experience, with a
      user-friendly website, secure payment options, and prompt delivery. Your
      trust and satisfaction mean everything to us, and we continuously work to
      exceed your expectations in every interaction.
    </p>
  </div>
</section>

{% endblock %}

Flask_FullStack_Ecommerce_App-main/website/templates/account.html
{%extends "base.html" %} {% block title%}Verve & Co.{%endblock%} {% block
content%}
<div class="small-container cart-page">
  {% with messages = get_flashed_messages()%} {% if messages%} {%for message in
  messages%}
  <div class="alert" style="background-color: #d1e7dd">
    <span class="closebtn" onclick="this.parentElement.style.display='none';"
      >&times;</span
    >
    <strong style="color: #256245">Success! {{message}}</strong>
  </div>
  {%endfor%} {%endif %} {%endwith%}
  <a class="btn" href="/logout">Logout</a>
  <a class="btn" style="background-color: #256245;" href="/admin">Admin Dashboard</a>
  <h1>Welcome, {{user_name}}</h1>
  <div>Your Orders:</div>
  <table class="cart">
    <tr>
      <th>Order ID</th>
      <th>Order</th>
    </tr>
    {%if orders == []%}
      <tr>You haven’t ordered anything</tr>
    {%else%} {% for order in orders %}
    <tr>
      <td>{{order[0]}}</td>
      <td>
        <a style="font-size: 1.2rem" href="/order/{{order[0]}}"
          >{{order[0]}}-{{order[3]}}</a
        >
      </td>
    </tr>
    {% endfor %} {%endif%}
  </table>
</div>
{%endblock%}

Flask_FullStack_Ecommerce_App-main/website/templates/all_products.html
{%extends "base.html"%} {% block title%}Our products{%endblock%} {%block
content%}
<div class="small-container">
  {% with messages = get_flashed_messages(category_filter=["info"])%} {%if
  messages%} {%for message in messages%}
  <div class="alert" style="background-color: #cfe2ff">
    <span class="closebtn" onclick="this.parentElement.style.display='none';"
      >&times;</span
    >
    <p style="color: #084298">
      <strong>{{message}}</strong>
    </p>
  </div>
  {%endfor%} {%endif %} {%endwith%}
  <form class="input-group" method="POST" action="/search">
    <input
      class="form-control"
      name="searchInput"
      type="search"
      placeholder="Search"
      aria-label="Search"
    />
    <button class="input-group-text" type="submit">Search</button>
  </form>

  {% with messages = get_flashed_messages(category_filter=["success"])%} {%if
  messages%} {%for message in messages%}
  <div class="alert" style="background-color: #cfe2ff">
    <span class="closebtn" onclick="this.parentElement.style.display='none';"
      >&times;</span
    >
    <p style="color: #084298">
      You have search for <strong>{{message}}</strong>
    </p>
  </div>
  {%endfor%} {%endif %} {%endwith%} {% with errors =
  get_flashed_messages(category_filter=["error"]) %} {% if errors %} {%for msg
  in errors %}
  <div class="alert" style="background-color: #f8d7da">
    <span class="closebtn" onclick="this.parentElement.style.display='none';"
      >&times;</span
    >
    <p style="color: #a12029">Error: <strong>{{msg}}</strong></p>
  </div>
  {% endfor %} {% endif %} {% endwith %}
  <div class="row row-2">
    <h2>All Products</h2>
    <form action="/sort-form" method="post">
      <div class="dropdown-section">
        <select name="sort-dropdown">
          <option value="Default Sort">Default Sort</option>
          <option value="Sort By Price">Sort By Price Asc</option>
          <option value="Sort By Price DESC">Sort By Price Desc</option>
          <option value="Sort By Rating">Sort By Rating</option>
          <option value="Sort By Brand">Sort By Brand</option>
        </select>
        <button class="btn" type="submit">
          <i class="fa fa-sort" aria-hidden="true"></i>
        </button>
      </div>
    </form>
  </div>
  <div class="row">
    {% for product in all_products%}
    <div class="col-4">
      <a href="/product_detail/{{product[0]}}"
        ><img
          style="aspect-ratio: 3/4; object-fit: cover"
          src="{{ product[5]}}"
      /></a>
      <div class="detail">
        <h4>{{product[1]}}</h4>
        {%set rate = product[3]|int%}

        <div class="rating">
          {%for i in range(0, rate) %}
          <i class="fa fa-star"></i>
          {%endfor%} {%for i in range(rate, 5) %}
          <i class="fa fa-star-o"></i>
          {%endfor%}
          <span style="margin-left: 2rem">{{product[2]}}</span>
          <p>{{product[6]}}</p>
        </div>
      </div>
    </div>
    {%endfor%}
  </div>
  <!-- <div class="page-btn">
      <span>1</span>
      <span>2</span>
      <span>3</span>
      <span>4</span>
      <span>&#8594;</span>
    </div> -->
</div>

{%endblock%}

Flask_FullStack_Ecommerce_App-main/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{%endblock%}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>

  <body>
    <div class="container">
      <div class="navbar">
        <div class="logo">
          <a href="/"
            ><img
              src="{{url_for('static', filename='images/shop-logo.png')}}"
              alt="logo"
              width="200px"
              style="border-radius: 8px"
          /></a>
        </div>
        <nav>
          <ul id="MenuItems">
            <li><a class="tab" href="/">Home</a></li>
            <li><a class="tab" href="/all_products">Products</a></li>
            <li><a class="tab" href="/about">About</a></li>
            <li><a class="tab" href="/contact">Contact</a></li>
            {% if user_name %}
            <li>
              <a href="/account"
                ><i class="fa-solid fa-user"></i> {{user_name}}</a
              >
            </li>
            {% else %}
            <li><a class="tab" href="/login">Login</a></li>
            {% endif %}
          </ul>
          <a href="/cart"
            ><img
              src="{{url_for('static', filename='images/shopping-cart.png')}}"
              width="30px"
              height="30px"
          /></a>
        </nav>
        <img
          src="{{ url_for('static', filename='/images/menu.png') }}"
          class="menu-icon"
          onclick="menutoggle()"
        />
      </div>
    </div>
    {% block content%} {% endblock %}

    <!-- Footer -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col-1">
            <h3>Download Our App</h3>
            <p>Download App for Android and ios mobile phone.</p>
            <div class="app-logo">
              <img
                src=" {{url_for('static', filename='images/google-play-badge.png')}}"
              />
              <img
                src=" {{url_for('static', filename='/images/app-store-badge.png')}}"
              />
            </div>
          </div>
          <div class="footer-col-2">
            <img
              src="{{url_for('static', filename='images/shop-logo.png')}}"
              alt="logo"
              width="200px"
              style="border-radius: 8px"
            />
            <p>
              Our Purpose Is To Sustainably Make the Pleasure and Benefits of
              Sports Accessible to the Many.
            </p>
          </div>
          <div class="footer-col-3">
            <h3>Quick Link</h3>
            <ul>
              <li>Privacy Policy</li>
              <li>Terms Of Use</li>
              <li>FAQ</li>
              <li>Contact</li>
            </ul>
          </div>
          <div class="footer-col-4">
            <h3>Follow Us</h3>
            <ul>
              <li>Facebook</li>
              <li>Twitter</li>
              <li>Instagram</li>
              <li>Youtube</li>
            </ul>
          </div>
        </div>
        <hr />
        <p class="copyright">Copyright 2023 - Verve & Co.</p>
      </div>
    </div>

    <!-- javascript -->

    <script>
      var MenuItems = document.getElementById("MenuItems");
      MenuItems.style.maxHeight = "0px";
      function menutoggle() {
        if (MenuItems.style.maxHeight == "0px") {
          MenuItems.style.maxHeight = "200px";
        } else {
          MenuItems.style.maxHeight = "0px";
        }
      }
      const navItems = document.getElementsByClassName("tab");
      for (let j = 0; j < navItems.length; j++) {
        if (navItems[j].href == location.href) {
          navItems[j].className = "active";
        }
      }
    </script>
  </body>
</html>

Flask_FullStack_Ecommerce_App-main/website/templates/cart.html
{%extends "base.html"%}{% block title%}Verve & Co. | Cart{%endblock%} {% block
content%}
<form action="{{url_for('views.CartUpdate')}}" method="post">
  <div class="small-container cart-page">
    <table>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Subtotal</th>
      </tr>
      {%set total = namespace(value=0)%} {% for row in cart %}
      <tr>
        <td>
          <div class="cart-info">
            <img src="{{row['image']}}" />
            <div>
              <p>{{row['name']}}</p>
              <small>Price: {{row['price']}}</small>
              <br />
              <button type="submit" name="delete-{{row['id']}}">Remove</button>
            </div>
          </div>
        </td>
        <td>
          <input
            type="number"
            min="0"
            value="{{row['quantity']}}"
            style="margin-right: 5px; width: 50px"
            name="quantity-{{row['id']}}"
          />
          <button type="submit" value="quantity-{{row['id']}}">Update</button>
        </td>
        <td>
          {{convert_int_to_currency(convert_currency_to_int(row['price']) *
          row['quantity'])}}
        </td>
      </tr>
      {%set total.value = total.value + (convert_currency_to_int(row['price']) *
      row['quantity'])%} {%endfor%}
    </table>
    <div class="total-price" style="margin-top: 2rem;">
      <table>
        <tr>
          <td>Subtotal</td>
          <td>{{convert_int_to_currency(total.value)}}</td>
        </tr>
        <tr>
          <td>Tax</td>
          <td>0</td>
        </tr>
        <tr>
          <td>Total</td>
          <td>{{convert_int_to_currency(total.value)}}</td>
        </tr>
      </table>
    </div>
  </div>
</form>
<div class="small-container cart-page" style="display: flex; justify-content: flex-end;">
  <form action="{{ url_for('views.proceed_cart') }}" method="post">
    <button
      type="submit"
      style="width: 200px; height: 40px; cursor: pointer"
      class="btn"
    >
      Proceed Cart
    </button>
  </form>
</div>
{%endblock%}

Flask_FullStack_Ecommerce_App-main/website/templates/orders.html
{%extends "base.html" %} {% block title%}Verve & Co.{%endblock%} {% block
content%}
<div class="small-container cart-page">
  <h1>Order Details - Order ID: {{ order[0] }}</h1>
  <p>Status : {{ order[3]}}</p>
  <h2>Order Items</h2>
  <table class="cart">
    <tr>
      <th>ProductID</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
    {%set total = namespace(value=0)%} {% for item in order_details %}
    <tr>
      <td>{{ item[1] }}</td>
      <td>{{ item[2] }}</td>
      <td>{{ item[3] }}</td>
    </tr>
    {%set total.value = total.value + (convert_currency_to_int(item[2]) *
    item[3])%} {%endfor%}
  </table>
  <div class="total-price" style="margin-top: 2rem;">
    <table>
      <tr>
        <td>Total</td>
        <td>{{convert_int_to_currency(total.value)}}</td>
      </tr>
    </table>
  </div>
</div>
{%endblock%}

Flask_FullStack_Ecommerce_App-main/website/templates/signup.html
{%extends "base.html"%} {% block title%}Verve & Co. | Sign up{%endblock%} {% block content%}
<div class="account-page">
  <div class="container">
    <div class="row">
      <div class="col-2">
        <img
          src="https://images.pexels.com/photos/5632402/pexels-photo-5632402.jpeg?auto=compress&cs=tinysrgb&w=600"
          width="100%"
        />
      </div>
      <div class="col-2">
        <div class="form-container">
          <div class="form-btn">
            <a href="/login" >Login</a>
            <a href="/signup" style="border-bottom: 3px solid #00aedf; padding-bottom: 3px;">Register</a>
          </div>
          <form method="POST" action="{{ url_for('auth.sign_up') }}">
            <h2 style="margin-bottom: 2rem;">Sign Up</h2>
            <div class="form-group">
              <label for="username">Username</label>
              <input
                type="text"
                id="username"
                name="username"
                class="form-control"
                placeholder="Enter Username"
                required
              />
              <span class="validation">{{ username_error }}</span>
              <label for="email">Email Address</label>
              <input
                type="email"
                id="email"
                name="email"
                class="form-control"
                placeholder="Enter Email"
                required
              />
              <span class="validation">{{ email_error }}</span>
              <label for="password">Password</label>
              <input
                type="password"
                id="password"
                name="password"
                class="form-control"
                placeholder="Enter Password"
                required
              />
              <span class="validation">{{ password_error }}</span>
              <br />
              <div>
                <button class="btn btn-primary" type="submit">Sign Up</button>
              </div>
            </div>
          </form>
          <p class="message">{{ registeration_success }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}